service:
  name: crud-lambda-typescript-mongo
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  healthCheck:
    handler: src/healthCheck.healthCheck
    events:
      - http:
          method: get
          path: healthcheck

  getAllBooks:
    handler: src/read.getAllBooks
    events:
      - http:
          method: get
          path: books
  
  getBooksPaginated:
    handler: src/read.getBooksPaginated
    events:
      - http:
          method: get
          path: paginated-books

  getSingleBook:
    handler: src/read.getSingleBook
    events:
      - http:
          method: get
          path: books/{id}

  deleteBook:
    handler: src/delete.deleteBook
    events:
      - http:
          method: delete
          path: books/{id}

  updateBook:
    handler: src/update.updateBook
    events:
      - http:
          method: post
          path: books/{id}

  insertBook:
    handler: src/create.insertBook
    events:
      - http:
          method: put
          path: books
